# DAT113 – Practice Set C (Strict syllabus only)

This set is designed to use **only** the notions listed for:
- DataFrame basics (structured data)
- subset selection / filtering / sorting
- Series, DataFrame, Index (incl. alignment concept)
- constructing DataFrames (lists, dicts, CSV)
- `size`, `value_counts`, `unique`, `nunique`
- missing values (`isna`, `fillna`)
- new columns with `map`, `replace`, `apply`

**Explicitly avoided**: `groupby`, `pivot_table`, joins/merges, `idxmax`, `stack`, advanced reshaping.

---

## Exercise C1 – Flight Prices (filter + sort)

Filter the flights where:
- `origin == 'MRS'`
- `price_eur <= 120`

Then sort by `price_eur` ascending.

Store the resulting DataFrame in `mrs_cheapest`.

In [ ]:
import pandas as pd

flights = pd.DataFrame({
    "origin": ["MRS","MRS","LYS","MRS","CDG","MRS"],
    "dest":   ["CDG","NCE","CDG","BCN","MRS","NCE"],
    "price_eur":[110, 140, 95, 120, 105, 80],
    "airline":["A","B","A","C","B","A"]
})

mrs_cheapest = flights.loc[(flights["origin"]=="MRS") & (flights["price_eur"]<=120)].sort_values("price_eur")
mrs_cheapest

  origin dest  price_eur airline
5    MRS  NCE         80       A
0    MRS  CDG        110       A
3    MRS  BCN        120       C

## Exercise C2 – App Installs (value_counts)

Use `value_counts()` on `platform`.

Store:
- the counts Series in `platform_counts`
- the most frequent platform name in `top_platform` (no `idxmax`)

In [26]:
import pandas as pd

installs = pd.DataFrame({
    "user": ["u1","u2","u3","u4","u5","u6","u7"],
    "platform": ["iOS","Android","Android","iOS","Android","Android","iOS"]
})

platform_counts= installs["platform"].value_counts()
top_platform = platform_counts.idxmax()
top_platform2 = platform_counts.sort_values(ascending=False).index[0]
top_platform2

'Android'

In [3]:
import pandas as pd

installs = pd.DataFrame({
    "user": ["u1","u2","u3","u4","u5","u6","u7"],
    "platform": ["iOS","Android","Android","iOS","Android","Android","iOS"]
})

platform_counts = installs["platform"].value_counts()
top_platform = platform_counts.sort_values(ascending=False).index[0]
print(platform_counts)
top_platform

platform
Android    4
iOS        3
Name: count, dtype: int64

'Android'

## Exercise C3 – Workout Types (unique & nunique)

1) Store the array of unique workout types in `workouts_unique`.
2) Store the number of unique athletes in `n_athletes`.

In [31]:
import pandas as pd

workouts = pd.DataFrame({
    "athlete": ["a1","a2","a1","a3","a2","a4"],
    "type": ["run","bike","swim","run","run","swim"]
})

workouts_unique = workouts["type"].unique()
n_athletes = int(workouts["athlete"].nunique())
workouts_unique, n_athletes

(array(['run', 'bike', 'swim'], dtype=object), 4)

In [60]:
import pandas as pd

workouts = pd.DataFrame({
    "athlete": ["a1","a2","a1","a3","a2","a4"],
    "type": ["run","bike","swim","run","run","swim"]
})

workout_unique = workouts["type"].unique()
n_athletes = int(workouts["athlete"].nunique())

workout_unique, n_athletes

(array(['run', 'bike', 'swim'], dtype=object), 4)

## Exercise C4 – Matrix Data (shape & size)

Compute:
- `n_rows` (number of rows)
- `n_cols` (number of columns)
- `n_elements` (df.size)
- `check` (boolean verifying `n_rows * n_cols == n_elements`)

In [36]:
import pandas as pd

df = pd.DataFrame({
    "x": [1, 2, 3],
    "y": [10, 20, 30],
    "z": [100, 200, 300]
})

n_rows, n_cols = df.shape
n_elements = df.size
check = n_rows * n_cols == n_elements
n_rows, n_cols, n_elements, check

(3, 3, 9, True)

In [63]:
import pandas as pd

df = pd.DataFrame({
    "x": [1, 2, 3],
    "y": [10, 20, 30],
    "z": [100, 200, 300]
})

n_rows, n_cols = df.shape

n_elements = df.size

check = n_rows*n_cols == n_elements

n_rows, n_cols,n_elements,check

(3, 3, 9, True)

## Exercise C5 – Daily Steps (missing values)

1) Count how many missing values are in `steps` and store it in `n_missing_steps`.
2) Create `steps_filled` where missing `steps` are filled with the median.

In [40]:
import pandas as pd
import numpy as np

steps = pd.DataFrame({
    "day": ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
    "steps": [8000, None, 12000, 5000, None, 15000, 7000]
})
n_missing_steps = steps["steps"].isna().sum()
steps_filled = steps.copy()
steps_filled["steps"] = steps_filled["steps"].fillna(steps_filled["steps"].mean())
steps_filled

   day    steps
0  Mon   8000.0
1  Tue   9400.0
2  Wed  12000.0
3  Thu   5000.0
4  Fri   9400.0
5  Sat  15000.0
6  Sun   7000.0

In [7]:
import pandas as pd
import numpy as np

steps = pd.DataFrame({
    "day": ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
    "steps": [8000, None, 12000, 5000, None, 15000, 7000]
})
n_missing_steps = int(steps["steps"].isna().sum())

steps_filled = steps.copy()


steps_filled["steps"] = steps_filled["steps"].fillna(steps_filled["steps"].median())
n_missing_steps, steps_filled

(2,
    day    steps
 0  Mon   8000.0
 1  Tue   8000.0
 2  Wed  12000.0
 3  Thu   5000.0
 4  Fri   8000.0
 5  Sat  15000.0
 6  Sun   7000.0)

## Exercise C6 – Ticket Priority (map)

Create a new column `priority_num` from `priority` using this mapping:
`{'low':1, 'medium':2, 'high':3}`

Store the resulting DataFrame in `tickets_scored`.

In [41]:
import pandas as pd

tickets = pd.DataFrame({
    "id": [1,2,3,4,5],
    "priority": ["low","high","medium","low","high"]
})

mapping = {"low": 1, "medium": 2, "high": 3}
tickets["priority_num"]= tickets["priority"].map(mapping)
tickets

   id priority  priority_num
0   1      low             1
1   2     high             3
2   3   medium             2
3   4      low             1
4   5     high             3

In [73]:
import pandas as pd

tickets = pd.DataFrame({
    "id": [1,2,3,4,5],
    "priority": ["low","high","medium","low","high"]
})

mapping = {"low": 1, "medium": 2, "high": 3}

tickets_scored = tickets.copy()
tickets_scored["priority_num"]= tickets_scored["priority"].map(mapping)
tickets_scored

   id priority  priority_num
0   1      low             1
1   2     high             3
2   3   medium             2
3   4      low             1
4   5     high             3

## Exercise C7 – Text Normalization (replace)

Replace values in the `segment` column so that:
- `'vip'` becomes `'VIP'`
- `'regular'` becomes `'Standard'`

Store the updated DataFrame in `customers_clean`.

In [48]:
import pandas as pd

customers = pd.DataFrame({
    "customer": ["c1","c2","c3","c4"],
    "segment": ["vip","regular","regular","vip"]
})
customers_clean = customers.copy()
customers_clean["segment"] = customers_clean["segment"].replace({"vip": 'VIP' , 'regular':'Standard'})
customers_clean

  customer   segment
0       c1       VIP
1       c2  Standard
2       c3  Standard
3       c4       VIP

In [9]:
import pandas as pd

customers = pd.DataFrame({
    "customer": ["c1","c2","c3","c4"],
    "segment": ["vip","regular","regular","vip"]
})

customers_clean = customers.copy()
customers_clean["segment"]=customers_clean["segment"].replace({"vip": "VIP", "regular": "Standard"})
customers_clean

  customer   segment
0       c1       VIP
1       c2  Standard
2       c3  Standard
3       c4       VIP

## Exercise C8 – Comments Length (apply)

Create a new column `n_chars` with the number of characters in each `comment`.
Use `apply`.

Store the resulting DataFrame in `comments_len`.

In [52]:
import pandas as pd

comments = pd.DataFrame({
    "user": ["u1","u2","u3"],
    "comment": ["Nice!", "Could be better", "Amazing product"]
})
comments_len = comments.copy()
comments_len["n_chars"]= comments_len["comment"].apply(len)
comments_len

  user          comment  n_chars
0   u1            Nice!        5
1   u2  Could be better       15
2   u3  Amazing product       15

In [80]:
import pandas as pd

comments = pd.DataFrame({
    "user": ["u1","u2","u3"],
    "comment": ["Nice!", "Could be better", "Amazing product"]
})

comments_len = comments.copy()
comments_len["n_chars"]= comments_len["comment"].apply(len)
comments_len

  user          comment  n_chars
0   u1            Nice!        5
1   u2  Could be better       15
2   u3  Amazing product       15

## Exercise C9 – Index alignment (Series + DataFrame)

1) Create a DataFrame `prices` from `data_dict`.
2) Set `country` as the index.
3) Create a Series `vat` with VAT rates for:
- France: 0.20
- Germany: 0.19
- Spain: 0.21
4) Create a new column `price_with_vat` using **index alignment**:
`price_with_vat = price_eur * (1 + vat)`

Store the final DataFrame in `prices_vat`.

In [56]:
import pandas as pd

data_dict = {
    "country": ["France", "Germany", "Spain", "Italy"],
    "price_eur": [10.0, 12.0, 8.0, 9.0]
}
prices = pd.DataFrame(data_dict).set_index("country")
vat = pd.Series({"France" : 0.20, 'Germany':0.19,"Spain":0.21})
prices["price_with_vat"]=prices["price_eur"]*(1+vat)
prices

         price_eur  price_with_vat
country
France        10.0           12.00
Germany       12.0           14.28
Spain          8.0            9.68
Italy          9.0             NaN

In [82]:
import pandas as pd

data_dict = {
    "country": ["France", "Germany", "Spain", "Italy"],
    "price_eur": [10.0, 12.0, 8.0, 9.0]
}

price = pd.DataFrame(data_dict).set_index("country")
vat = pd.Series({"France" : 0.20, "Germany" : 0.19, "Spain" : 0.21})

price["price_with_vat"] = price["price_eur"]*(1+vat)
price

         price_eur  price_with_vat
country
France        10.0           12.00
Germany       12.0           14.28
Spain          8.0            9.68
Italy          9.0             NaN

## Exercise C10 – CSV Weather (read_csv + exploration)

Read the CSV file at `csv_path` into a DataFrame `weather`.

Then compute:
- `n_cities` = number of unique cities (`nunique`)
- `city_counts` = counts per city (`value_counts`)

Store the results in the variables above.

In [88]:
import pandas as pd
from pathlib import Path

csv_path = Path("weather_sample.csv")

# Create the CSV file (do not modify this cell)
csv_path.write_text(
    "city,temp\n"
    "Paris,7\n"
    "Lyon,5\n"
    "Paris,8\n"
    "Marseille,10\n"
    "Lyon,6\n",
    encoding="utf-8"
)

weather = pd.read_csv(csv_path)
n_city = int(weather["city"].nunique())
city_counts = weather["city"].value_counts()
n_city, city_counts

(3,
 city
 Paris        2
 Lyon         2
 Marseille    1
 Name: count, dtype: int64)

---

End of Practice Set C.